services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - ADMIN_USER=admin
      - ADMIN_PASS=vmq_gateway
    depends_on:
      - mongo

volumes:
  mongo_data:
